version: "3.9"

services:


  consul:
    image: consul:1.15.4
    command: agent -server -ui -bootstrap-expect=1 -client=0.0.0.0
    ports:
      - "8500:8500"


  frontend:
    build: ./frontend
    ports:
      - "5001:5001"
    environment:
      CONSUL_HOST: consul
      SERVICE_NAME: front-service
      SERVICE_PORT: 5001
      SERVICE_HOST: frontend
    depends_on:
      - consul
      - microusers
      - microproductos


  microusers:
    build: ./microUsers
    ports:
      - "5002:5002"
    environment:
      CONSUL_HOST: consul
      SERVICE_NAME: users-service
      SERVICE_PORT: 5002
      SERVICE_HOST: microusers
      MYSQL_HOST: db_users
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: myflaskapp
    depends_on:
      - consul
      - db_users

  db_users:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db_users/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5


  microproductos:
    build: ./microProductos
    ports:
      - "5003:5003"
    environment:
      CONSUL_HOST: consul
      SERVICE_NAME: products-service
      SERVICE_PORT: 5003
      SERVICE_HOST: microproductos
      MYSQL_HOST: db_productos
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: productos
    depends_on:
      - consul
      - db_productos
          
  db_productos:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db_products/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  microorders:
    build: ./microOrders
    ports:
      - "5004:5004"
    depends_on:
      db_orders:
        condition: service_healthy
    environment:
      CONSUL_HOST: consul
      MYSQL_HOST: db_orders

  db_orders:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db_orders/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5

volumes:
  users_data:
  productos_data: